{
 "title": "Tabla",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Archivos Vigilados",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM registros_archivos WHERE evento = 'BASELINE';"
    }
   ]
  },
  {
   "title": "Alertas Críticas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM registros_archivos WHERE evento != 'BASELINE';"
    }
   ]
  },
  {
   "title": "Distribución Histórica de Eventos",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  evento AS metric, \r\n  count(evento) AS value \r\nFROM registros_archivos WHERE evento != 'BASELINE'\r\nGROUP BY evento ;"
    }
   ]
  },
  {
   "title": "Línea de Tiempo de Monitoreo FIM",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(fecha_registro,'1m'),\r\n  evento AS metric,\r\n  count(evento) AS value\r\nFROM registros_archivos\r\nWHERE $__timeFilter(fecha_registro)\r\nGROUP BY 1, 2\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Registro Criptográfico y Evidencia de Ataques",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\nfecha_registro AS \"Fecha y Hora\",\r\nnombre_archivo AS \"Archivo Modificado\",\r\nevento AS \"Tipo de Alerta\",\r\nruta_completa AS \"Ruta Completa\",\r\ndetalles_diff AS \"Evidencia / Texto Inyectado\",\r\nhash_sha256 AS \"SHA256\",\r\nhash_md5 AS \"MD5\",\r\npropietario AS \"Propietario\",\r\npermisos AS \"Permisos\"\r\nFROM registros_archivos\r\nORDER BY fecha_registro DESC;"
    }
   ]
  }
 ]
}